"""
Trace the Beatsmaxxer Pro logo art into SVG paths for the splash.

The splash fills these silhouettes with its own palette, so the letterforms
match the art while the colours stay a CSS knob. Rerun after replacing
logo-source.webp:

    uv run --with opencv-python-headless --with pillow --with numpy python trace.py

Writes ../../src/lib/components/splashLogoPaths.ts (coordinates are the art's
2000 x 848 pixels).
"""
import numpy as np, cv2
from PIL import Image
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE.parent.parent / 'src/lib/components/splashLogoPaths.ts'

im = np.array(Image.open(HERE / 'logo-source.webp').convert('RGB'))
hsv = cv2.cvtColor(im, cv2.COLOR_RGB2HSV).astype(int)
H, S, V = hsv[..., 0], hsv[..., 1], hsv[..., 2]
yy, xx = np.mgrid[0:im.shape[0], 0:im.shape[1]]

bright = V > 90
green = bright & (H >= 36) & (H <= 70) & (S > 90)
bluish = bright & (H >= 95) & (H <= 150)
warm = bright & ~green & ~bluish
pro_box = (xx > 1225) & (xx < 1700) & (yy > 540) & (yy < 660)


def clean(mask, close=(5, 3)):
    m = mask.astype(np.uint8) * 255
    # Bridge the art's scanline gaps so each letter traces as one shape.
    m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_RECT, close))
    # Soften pixel stair-steps before tracing.
    m = cv2.GaussianBlur(m, (3, 3), 0)
    return (m > 127).astype(np.uint8)


def keep(mask, min_area, band=None):
    n, lab, stats, _ = cv2.connectedComponentsWithStats(mask, 8)
    out = np.zeros_like(mask)
    for i in range(1, n):
        x, y, w, h, area = stats[i]
        if area < min_area:
            continue
        if band and (y + h < band[0] or y > band[1]):
            continue
        out[lab == i] = 1
    return out


def to_path(mask, eps=0.9):
    contours, _ = cv2.findContours(mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
    parts = []
    for c in contours:
        if cv2.contourArea(c) < 12:
            continue
        pts = cv2.approxPolyDP(c, eps, True).reshape(-1, 2)
        if len(pts) < 3:
            continue
        parts.append('M' + ' '.join(f'{x} {y}' for x, y in pts) + 'Z')
    return ''.join(parts)


word = keep(clean(warm & ~pro_box), 900, band=(280, 600))
pro = keep(clean(bright & pro_box, close=(3, 5)), 60)
bolt = keep(clean(green), 4000)
# The word hides the bolt's middle in the art, but the splash shows the bolt
# alone before the word lands. Bridge the two visible halves with the hull of
# the rows either side of the gap.
rows = np.zeros_like(bolt)
rows[230:300] = bolt[230:300]
rows[540:600] = bolt[540:600]
pts = cv2.findNonZero(rows)
if pts is not None:
    cv2.fillConvexPoly(bolt, cv2.convexHull(pts), 1)

paths = {'WORD': to_path(word), 'PRO': to_path(pro), 'BOLT': to_path(bolt)}

dbg = np.zeros_like(im)
dbg[bolt > 0] = (60, 255, 60)
dbg[word > 0] = (255, 140, 80)
dbg[pro > 0] = (255, 255, 255)
Image.fromarray(dbg).resize((1000, 424)).save(HERE / 'trace-debug.png')

lines = [
    '// Generated by svelte/scripts/splash/trace.py from logo-source.webp. Do not edit.',
    '// Coordinates are the art board: 2000 x 848.',
    '',
]
for k, d in paths.items():
    lines.append(f"export const LOGO_{k} = '{d}';")
OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
print({k: len(v) for k, v in paths.items()}, OUT.stat().st_size)
